### PR TITLE
add missed prev/next onclick handlers

### PR DESCRIPTION
**Pull request by YuriSn**

### CODE REVIEW

**Comment by StevenIseki** [comment]
@YuriSn If you feel like extending react-swipr a bit more let me know, I can add you as a collaborator Thanks for your help!

**Comment by YuriSn** [comment]
@StevenIseki It would be nice if you add me to collaborators. I have a few ideas to expand the functionality. I will try to implement them. And I have one question. After merging a request does not start npm build command. Are you doing it manually? Thanks for the good package! :)

**Comment by StevenIseki** [comment]
I have never heard of that, how do you do that, with codeshop or travis ci?
I am running npm publish. I will add you as collaborator now, if you are pushing a lot I can allow you to publish on npm, but having it run automatically on merge could be nice. Would have to increment the version too.

**Comment by YuriSn** [comment]
I apologize that I was gone for a long time. Before, I did not publish npm packages. Therefore, I not fully understand this process. In my spare time I try to explore the deployment and integration packages with ci. At the moment in your package changed only the code that I changed directly in the react. But the `npm build` command was not running and the code in the bundle (lib dir) not changed. When the build process should be run?

**Comment by StevenIseki** [comment]
Okay I just run `npm run build` and then test the example is all working `npm start` then increment the version and publish `npm version patch`, `git add -A`, `git push` and `npm publish`

I run this manually just on the local repo, I published the recent changes `2.0.6` let me know if its okay.

**Comment by YuriSn** [comment]
All ok now thank you.

**Pull request merged**
